version: '3.8'

services:
#  app:
#    image: php:8.1-apache-kevin
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    container_name: php
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - .:/var/www/html
#      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf

  nginx:
    image: nginx:1.25.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - php

  php:
    image: php:8.2.15-fpm-kevin
    ports:
      - "9000:9000"
    build:
      context: .
      dockerfile: ./Dockerfile.fpm
    environment:
      - XDEBUG_SESSION=1
      - XDEBUG_MODE=develop,profile,debug
      - XDEBUG_CONFIG=client_host=172.16.17.11 client_port=9003 log=/tmp/xdebug.log
      - PHP_IDE_CONFIG=serverName=webdav
    volumes:
      - .:/var/www/html
